### ISSUE TITLE
How does Lua Injection work? (UnlockFPS)

### ISSUE THREAD

**Issue by EnderNon** [FireflyClub/FireflyCore#1]
I'm curious about how it works - looking at https://github.com/FireflyClub/FireflyCore/blob/main/src/main/java/emu/lunarcore/command/commands/UnlockFPSCommand.java there's a Base64 encoded string that is decoded and does some kind of injection, how does it work?

**Comment by letheriver2007** [comment]
I am glad to discuss skill problems, but i thought u should not ask here but dm my discord (same name as github).
